name: Run benchmark tests in TeX Live

on: [push, pull_request]

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #version: [2022, 2023, 2024] # ppmcheckpdf not in texlive 2022
        version: [2023, 2024]
    steps:
    - uses: actions/checkout@v4
    - name: Install TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        version: ${{ matrix.version }}
        package-file: .github/workflows/texlive-package.txt
        packages: tabularray
        update-all-packages: true
    - name: Run benchmark tests with previous package
      run: |
        cd benchmarks
        pdflatex --interaction=nonstopmode tblrbenchmark.tex
        xelatex --interaction=nonstopmode tblrbenchmark.tex
        lualatex --interaction=nonstopmode tblrbenchmark.tex
    - name: Run benchmark tests with current package
      run: |
        cp tabularray.sty benchmarks/tabularray.sty
        cd benchmarks
        pdflatex --interaction=nonstopmode tblrbenchmark.tex
        xelatex --interaction=nonstopmode tblrbenchmark.tex
        lualatex --interaction=nonstopmode tblrbenchmark.tex
